---
ansible_host: "{{ host_ip }}"
ansible_user: "{{ server_admin_user }}"


projects_dir: /opt

plausible_project_dir: plausible
ntfy_project_dir: ntfy
radicale_project_dir: radicale

timezone: Europe/Copenhagen
